
/*
	JointStates.h
	This msg file was autogenerated by the Rutgers avr_bridge software.
	*/ 
#ifndef JOINTSTATES_H
#define JOINTSTATES_H
#include "Msg.h"
#include "vector.h"
#include "ros_string.h"


namespace tele_msgs {
class JointStates : public Msg{
   public:
	JointStates();
	JointStates(uint8_t * data);
	~JointStates();

	uint16_t bytes();
	uint16_t serialize(uint8_t * out_buffer);
	uint16_t deserialize(uint8_t * data);

	int32_t position_right;
	int32_t position_left;
	float velocity_right;
	float velocity_left;
   private:

}; /***** ending class JointStates *******/


} /***** ending namespace tele_msgs *******/

#endif  /****   JOINTSTATES_H    *****/