
/* This file was autogenerated as a part of the avr_bridge pkg

avr_bridge was written by 
Adam Stambler and Phillip Quiza of Rutgers University.

*/

#include "Ros.h"

char Ros::getTopicTag(char * topic){
if (strcmp(topic, "joint_states") ==0)
	 return 1;
if (strcmp(topic, "cmd_vel") ==0)
	 return 0;


	return 0;
}
Ros ros("tele_bridge", 2); //autogenerated Ros object