
/*
	VelocityCommand.h
 	This msg file was autogenerated by the Rutgers avr_bridge software.
 	*/
#ifndef VELOCITYCOMMAND_H
#define VELOCITYCOMMAND_H
#include "Msg.h"
#include "vector.h"
#include "ros_string.h"


namespace tele_msgs {
class VelocityCommand : 
  public Msg{
public:
    VelocityCommand();
    VelocityCommand(uint8_t * data);
    ~VelocityCommand();

    uint16_t bytes();
    uint16_t serialize(uint8_t * out_buffer);
    uint16_t deserialize(uint8_t * data);

    float velocity_right;
    float velocity_left;
private:

  }; /***** ending class VelocityCommand *******/


} /***** ending namespace tele_msgs *******/

#endif  /****   VELOCITYCOMMAND_H    *****/

